### ISSUE TITLE
Add flag to remove origin from fields

### ISSUE THREAD

**Issue by sd2k** [dsgallups/wasm-tracing#9]
Hey, thanks for creating this fork and maintaining it. I was wondering how you'd feel about also merging [this PR](https://github.com/old-storyai/tracing-wasm/pull/27) in to avoid the `origin` field with filename/line number being added? There's some justification in the [original issue](https://github.com/old-storyai/tracing-wasm/issues/26).

(Maybe there's a more nuanced solution like allowing the user to filter the fields somehow, not sure what you'd prefer!)

**Comment by dsgallups** [comment]
Sounds great! I'll see about shipping that later this evening.

**Comment by dsgallups** [comment]
What I'll do is merge in the PR first for a release. Need to update changelog and push CI for playwright testing, and then can see about filtering the fields afterwards.

**Comment by dsgallups** [comment]
Update: Still WIP. Working on a test harness.

**Comment by dsgallups** [comment]
I've decided to skip the test harness. Manually reviewed config options with my bare eyes. The original implementation desires a rework. fixed in [#c8b17c2](https://github.com/dsgallups/wasm-tracing/pull/11/commits/c8b17c2033422ef25cfe495ca5fa5837e8ba611d)

**Comment by sd2k** [comment]
Nice, thanks! :partying_face:
